export const CHANGE_PAGE_NUMBER = 'CHANGE_PAGE_NUMBER';
export const CHANGE_TOTAL_VISIBLE = 'CHANGE_TOTAL_VISIBLE';
export const CHANGE_FIRST_COLUMN = 'CHANGE_FIRST_COLUMN';
export const CHANGE_DISPLAY_COLUMN = 'CHANGE_DISPLAY_COLUMN';